services:
  - type: web
    name: ezgisude-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
